name: elevator
channels:
  - defaults
dependencies:
  - python=3.7
  - pytorch
  - matplotlib
  - plotly
  - pandas
  - pip
  - dash
  - conda-forge::dash-mantine-components
  - pip:
      - simpy
      - dash-iconify